### PR TITLE
Lookup plugin

### LINKED ISSUE #35: Example for plugin reading from stding or subcommand
Hello! 

I am writing a plugin that emulates [promptSearch from Xmonad's prompt](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Actions-Search.html). Basically, the user can configure urls (say duckduckgo or the rust std documentation) to look up to then bind a key for each of the urls.

I have it implemented for duckduckgo, but I'd like to read from stdin or a subcommand to change between different urls.  For instance:
* `dmenu --lookup --where=D`;
* `"D" | dmenu --lookup`;
* or maybe `dmenu --lookup=D`

would translate to https://duckduckgo.com/ + dmenu's prompt input.

The problem is that I am struggling to understand how to read stdin (or to add a subcommand). When I set a format_stdin function and set nostdin to false, it gets stuck.This is what I have working for now:
```rust
use overrider::*;
use std::io::Write;
use std::process::Command;

use crate::drw::Drw;
use crate::result::*;

#[override_flag(flag = lookup)]
impl Drw {
    // I know I need to implement format_stdin and put the logic to select the url there,
    // but I don't know how to access it on dispose
    pub fn format_input(&self) -> CompResult<String> {
	Ok(format!("[Search DDG]: {}",self.input))
    }
    pub fn dispose(&mut self, _output: String, recommendation: bool) -> CompResult<bool> {
	let eval = format!("https://duckduckgo.com/{}", self.input);
	self.input = "".to_owned();
	self.pseudo_globals.cursor = 0;
	if eval.len() > 0 {
	    let mut child = Command::new("xdg-open")
		.arg(eval.clone())
		.spawn()
		.map_err(|_| Die::Stderr("Failed to spawn child process".to_owned()))?;

	    child.stdin.as_mut().ok_or(Die::Stderr("Failed to open stdin of child process"
						   .to_owned()))?
	    .write_all(eval.as_bytes())
		.map_err(|_| Die::Stderr("Failed to write to stdin of child process"
					 .to_owned()))?;
	}
	self.draw()?;
	Ok(!recommendation)
    }
}

use crate::config::{ConfigDefault, DefaultWidth};
#[override_flag(flag = lookup)]
impl ConfigDefault {
    pub fn nostdin() -> bool {
        // setting this to false makes it get stuck
	true
    }
    pub fn render_flex() -> bool {
	true
    }
    pub fn render_default_width() -> DefaultWidth {
	DefaultWidth::Custom(25)
    }
}

```

### PR DESCRIPTION
**Pull request by carrascomj**
Closes #35 

### Description
Allow for a [promptSearch like in xmonad](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Actions-Search.html). Adds the **lookup** FLAG:
```
-L, --lookup
            The input in the prompt will be used as the search term in the selected engine (duckduckgo as default). XDG-
            OPEN will be used for opening the  links.
```
With the **engine** OPTION:
```
--engine <engine>
            Engine to look up into. Possible values: ["github", "rust", "archwiki", "ddg", "english"]. More engines can
            be added at lookup/main.rs
```
The usage accepts any of the following:
* `echo ddg | dmenu --lookup` will search the input from the prompt at [duckduckgo](https://duckduckgo.com/).
* `dmenu --engine=github --lookup` will search the input from the prompt at [github](https://github.com/search?q=).
* ``dmenu_run --engine=rust --lookup``will search the input from the input at [rust std docs](https://doc.rust-lang.org/std/?search=) using `dmenu_run`.

### Implementation
A `HashMap` with [once_cell](https://crates.io/crates/once_cell) is used for the mappings from the input to the engine. 
* not optimal because it allocates Strings as keys, but I was banging my head against a wall trying to get it to work with `&'static str`. 
* The reasoning behind this pattern is that the interested users could just add/remove entries to use the engines of their likings.
* It uses once_cell instead of [lazy_static](https://crates.io/crates/lazy_static) because the build stage was having problems to resolve the dependencies with `dmenu` and the plugin.

### CODE REVIEW

**Comment by Shizcow** [comment]
I'm impressed with how seamless this plugin is. Thanks for your contribution!

You mentioned `lazy_static` having some problems, which I'm not surprised about. I think `phf::map` could make things more optimal, but that increases dependency count by a lot. Then again this project already has ~300 dependencies when fully loaded anyway so I don't care either way.

I see you're still making some tweaks so I'll merge tomorrow morning. Minor changes I'd love (but can totally do myself):
- Search engines: can we get docs.rs and crates.io?
- Error message on invalid engine: something like `Invalid search engine 'dd'. Valid options are: 'ddg', 'archwiki', and 'rust'` instead of the current `invalid engine`

**Comment by carrascomj** [comment]
Cool! I implemented your suggestions and it is ready from my side. Feel free to change whatever you want (maybe you prefer other names for the engines, I just picked whatever was easy to read).

**Comment by Shizcow** [comment]
Thanks for the edits. Looking forward to putting `echo -e "crates\ngithub\nrust\nddg\nenglish\ndocs" | dmenu | dmenu --lookup` somewhere is my dotfiles :+1:

**Comment by Shizcow** [comment]
After a week of frequent use, I've addressed minor areas of improvement. Everything's documented in `make plugins` and `dmenu --help`, but here's an overview:  
- Added `--list-engines`
- Moved from `once_cell` to `phf`
- Changed search engine syntax to include `%s`, similar to how most browsers work
- Documentation edits
- Changed `english` to `dictionary` and added `thesaurus` for completion

This now simplifies the lookup command in my previous comment to:
```sh
dmenu --lookup --list-engines | dmenu | dmenu --lookup
```

**Comment by carrascomj** [comment]
That's very convenient, I like it :+1:

**Pull request merged**
